baseURL = "http://example.org/"
languageCode = "en-us"
title = "Eve's recipe collection"
theme = "eve-theme"
[outputs]
  home = ["HTML"]
  page = ["HTML"]
  [related]
  treshold = 100
  includeNewer = true
  toLower = true

  [[related.indices]]
      name = "categories"
      weight = 1
[taxonomies]
  tag = "tags"
  category = "categories"